//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExplorerNet.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double HeightLevel {
            get {
                return ((double)(this["HeightLevel"]));
            }
            set {
                this["HeightLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public double WidthFilepanel {
            get {
                return ((double)(this["WidthFilepanel"]));
            }
            set {
                this["WidthFilepanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ShowDialog")]
        public global::ExplorerNet.CopyWindowApps.FileOverwriteOptionKind FileOverwriteOption {
            get {
                return ((global::ExplorerNet.CopyWindowApps.FileOverwriteOptionKind)(this["FileOverwriteOption"]));
            }
            set {
                this["FileOverwriteOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::ExplorerNet.ViewWindowApps.Templates.ViewWindowTemplate LastTemplate {
            get {
                return ((global::ExplorerNet.ViewWindowApps.Templates.ViewWindowTemplate)(this["LastTemplate"]));
            }
            set {
                this["LastTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public double FilepanelIcoWidth {
            get {
                return ((double)(this["FilepanelIcoWidth"]));
            }
            set {
                this["FilepanelIcoWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double FilepanelNameWidth {
            get {
                return ((double)(this["FilepanelNameWidth"]));
            }
            set {
                this["FilepanelNameWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public double FilepanelSizeWidth {
            get {
                return ((double)(this["FilepanelSizeWidth"]));
            }
            set {
                this["FilepanelSizeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NaN")]
        public double ViewWindowTop {
            get {
                return ((double)(this["ViewWindowTop"]));
            }
            set {
                this["ViewWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NaN")]
        public double ViewWindowLeft {
            get {
                return ((double)(this["ViewWindowLeft"]));
            }
            set {
                this["ViewWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double ViewWindowHeight {
            get {
                return ((double)(this["ViewWindowHeight"]));
            }
            set {
                this["ViewWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double ViewWindowWidth {
            get {
                return ((double)(this["ViewWindowWidth"]));
            }
            set {
                this["ViewWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.WindowState ViewWindowState {
            get {
                return ((global::System.Windows.WindowState)(this["ViewWindowState"]));
            }
            set {
                this["ViewWindowState"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".enet")]
        public string FileAppExtention {
            get {
                return ((string)(this["FileAppExtention"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rainierpurple")]
        public string CurrentSkin {
            get {
                return ((string)(this["CurrentSkin"]));
            }
            set {
                this["CurrentSkin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Default)")]
        public global::System.Globalization.CultureInfo CurrentCulture {
            get {
                return ((global::System.Globalization.CultureInfo)(this["CurrentCulture"]));
            }
            set {
                this["CurrentCulture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::ExplorerNet.Tools.RecentTemplateNS.RecentTemplates RecentTemplates {
            get {
                return ((global::ExplorerNet.Tools.RecentTemplateNS.RecentTemplates)(this["RecentTemplates"]));
            }
            set {
                this["RecentTemplates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrLang {
            get {
                return ((string)(this["CurrLang"]));
            }
            set {
                this["CurrLang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LanguageSelectorVisible {
            get {
                return ((bool)(this["LanguageSelectorVisible"]));
            }
            set {
                this["LanguageSelectorVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::ExplorerNet.Tools.ViewSettings.ViewLocations ViewLocations {
            get {
                return ((global::ExplorerNet.Tools.ViewSettings.ViewLocations)(this["ViewLocations"]));
            }
            set {
                this["ViewLocations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastNameAssemblie {
            get {
                return ((string)(this["LastNameAssemblie"]));
            }
            set {
                this["LastNameAssemblie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::ExplorerNet.Tools.LastStartedFiles.LastStartedFiles LastStartedFiles {
            get {
                return ((global::ExplorerNet.Tools.LastStartedFiles.LastStartedFiles)(this["LastStartedFiles"]));
            }
            set {
                this["LastStartedFiles"] = value;
            }
        }
    }
}
